<?php

use Illuminate\Database\Seeder;
use App\Municipio;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Municipio::create([ 'dpa' =>  "25.03", 'nombre' => "Martí" ]);
        Municipio::create([ 'dpa' =>  "25.02", 'nombre' => "Cárdenas" ]);
        Municipio::create([ 'dpa' =>  "23.06", 'nombre' => "Habana del Este" ]);
        Municipio::create([ 'dpa' =>  "24.04", 'nombre' => "Santa Cruz del Norte" ]);
        Municipio::create([ 'dpa' =>  "23.03", 'nombre' => "Centro Habana" ]);
        Municipio::create([ 'dpa' =>  "23.05", 'nombre' => "Regla" ]);
        Municipio::create([ 'dpa' =>  "26.03", 'nombre' => "Sagua La Grande" ]);
        Municipio::create([ 'dpa' =>  "23.02", 'nombre' => "Plaza de la Revolución" ]);
        Municipio::create([ 'dpa' =>  "23.04", 'nombre' => "La Habana Vieja" ]);
        Municipio::create([ 'dpa' =>  "23.10", 'nombre' => "Cerro" ]);
        Municipio::create([ 'dpa' =>  "23.09", 'nombre' => "Diez de Octubre" ]);
        Municipio::create([ 'dpa' =>  "23.07", 'nombre' => "Guanabacoa" ]);
        Municipio::create([ 'dpa' =>  "23.08", 'nombre' => "San Miguel del Padrón" ]);
        Municipio::create([ 'dpa' =>  "23.01", 'nombre' => "Playa" ]);
        Municipio::create([ 'dpa' =>  "23.14", 'nombre' => "Arroyo Naranjo" ]);
        Municipio::create([ 'dpa' =>  "23.13", 'nombre' => "Boyeros" ]);
        Municipio::create([ 'dpa' =>  "23.11", 'nombre' => "Marianao" ]);
        Municipio::create([ 'dpa' =>  "24.02", 'nombre' => "San José de las Lajas" ]);
        Municipio::create([ 'dpa' =>  "24.03", 'nombre' => "Jaruco" ]);
        Municipio::create([ 'dpa' =>  "23.15", 'nombre' => "Cotorro" ]);
        Municipio::create([ 'dpa' =>  "23.12", 'nombre' => "La Lisa" ]);
        Municipio::create([ 'dpa' =>  "22.05", 'nombre' => "Bauta" ]);
        Municipio::create([ 'dpa' =>  "25.01", 'nombre' => "Matanzas" ]);
        Municipio::create([ 'dpa' =>  "22.04", 'nombre' => "Caimito" ]);
        Municipio::create([ 'dpa' =>  "24.05", 'nombre' => "Madruga" ]);
        Municipio::create([ 'dpa' =>  "25.08", 'nombre' => "Limonar" ]);
        Municipio::create([ 'dpa' =>  "26.01", 'nombre' => "Corralillo" ]);
        Municipio::create([ 'dpa' =>  "22.02", 'nombre' => "Mariel" ]);
        Municipio::create([ 'dpa' =>  "24.01", 'nombre' => "Bejucal" ]);
        Municipio::create([ 'dpa' =>  "22.01", 'nombre' => "Bahía Honda" ]);
        Municipio::create([ 'dpa' =>  "22.06", 'nombre' => "San Antonio de los Baños" ]);
        Municipio::create([ 'dpa' =>  "22.09", 'nombre' => "Artemisa" ]);
        Municipio::create([ 'dpa' =>  "22.03", 'nombre' => "Guanajay" ]);
        Municipio::create([ 'dpa' =>  "26.02", 'nombre' => "Quemado de Güines" ]);
        Municipio::create([ 'dpa' =>  "21.05", 'nombre' => "La Palma" ]);
        Municipio::create([ 'dpa' =>  "24.11", 'nombre' => "Quivicán" ]);
        Municipio::create([ 'dpa' =>  "24.08", 'nombre' => "Güines" ]);
        Municipio::create([ 'dpa' =>  "25.09", 'nombre' => "Unión de Reyes" ]);
        Municipio::create([ 'dpa' =>  "24.07", 'nombre' => "San Nicolás" ]);
        Municipio::create([ 'dpa' =>  "24.06", 'nombre' => "Nueva Paz" ]);
        Municipio::create([ 'dpa' =>  "25.05", 'nombre' => "Perico" ]);
        Municipio::create([ 'dpa' =>  "25.06", 'nombre' => "Jovellanos" ]);
        Municipio::create([ 'dpa' =>  "22.08", 'nombre' => "Alquízar" ]);
        Municipio::create([ 'dpa' =>  "25.07", 'nombre' => "Pedro Betancourt" ]);
        Municipio::create([ 'dpa' =>  "22.07", 'nombre' => "Güira de Melena" ]);
        Municipio::create([ 'dpa' =>  "22.10", 'nombre' => "Candelaria" ]);
        Municipio::create([ 'dpa' =>  "24.10", 'nombre' => "Batabanó" ]);
        Municipio::create([ 'dpa' =>  "25.13", 'nombre' => "Los Arabos" ]);
        Municipio::create([ 'dpa' =>  "24.09", 'nombre' => "Melena del Sur" ]);
        Municipio::create([ 'dpa' =>  "25.04", 'nombre' => "Colón" ]);
        Municipio::create([ 'dpa' =>  "21.04", 'nombre' => "Viñales" ]);
        Municipio::create([ 'dpa' =>  "22.11", 'nombre' => "San Cristóbal" ]);
        Municipio::create([ 'dpa' =>  "26.11", 'nombre' => "Santo Domingo" ]);
        Municipio::create([ 'dpa' =>  "26.10", 'nombre' => "Cifuentes" ]);
        Municipio::create([ 'dpa' =>  "25.11", 'nombre' => "Jagüey Grande" ]);
        Municipio::create([ 'dpa' =>  "21.06", 'nombre' => "Los Palacios" ]);
        Municipio::create([ 'dpa' =>  "25.12", 'nombre' => "Calimete" ]);
        Municipio::create([ 'dpa' =>  "21.03", 'nombre' => "Minas de Matahambre" ]);
        Municipio::create([ 'dpa' =>  "21.07", 'nombre' => "Consolación del sur" ]);
        Municipio::create([ 'dpa' =>  "21.02", 'nombre' => "Mantua" ]);
        Municipio::create([ 'dpa' =>  "27.02", 'nombre' => "Rodas" ]);
        Municipio::create([ 'dpa' =>  "26.12", 'nombre' => "Ranchuelo" ]);
        Municipio::create([ 'dpa' =>  "27.04", 'nombre' => "Lajas" ]);
        Municipio::create([ 'dpa' =>  "25.10", 'nombre' => "Cienaga de Zapata" ]);
        Municipio::create([ 'dpa' =>  "26.09", 'nombre' => "Santa Clara" ]);
        Municipio::create([ 'dpa' =>  "21.08", 'nombre' => "Pinar del Río" ]);
        Municipio::create([ 'dpa' =>  "27.01", 'nombre' => "Aguada de Pasajeros" ]);
        Municipio::create([ 'dpa' =>  "26.13", 'nombre' => "Manicaragua" ]);
        Municipio::create([ 'dpa' =>  "21.10", 'nombre' => "San Juan y Martínez" ]);
        Municipio::create([ 'dpa' =>  "21.11", 'nombre' => "Guane" ]);
        Municipio::create([ 'dpa' =>  "27.03", 'nombre' => "Palmira" ]);
        Municipio::create([ 'dpa' =>  "27.05", 'nombre' => "Cruces" ]);
        Municipio::create([ 'dpa' =>  "27.06", 'nombre' => "Cumanayagua" ]);
        Municipio::create([ 'dpa' =>  "27.07", 'nombre' => "Cienfuegos" ]);
        Municipio::create([ 'dpa' =>  "27.08", 'nombre' => "Abreus" ]);
        Municipio::create([ 'dpa' =>  "21.09", 'nombre' => "San Luis" ]);
        Municipio::create([ 'dpa' =>  "21.01", 'nombre' => "Sandino" ]);
        Municipio::create([ 'dpa' =>  "40.01", 'nombre' => "Isla de la Juventud" ]);
        Municipio::create([ 'dpa' =>  "28.06", 'nombre' => "Trinidad" ]);
        Municipio::create([ 'dpa' =>  "26.04", 'nombre' => "Encrucijada" ]);
        Municipio::create([ 'dpa' =>  "29.01", 'nombre' => "Chambas" ]);
        Municipio::create([ 'dpa' =>  "26.05", 'nombre' => "Camajuaní" ]);
        Municipio::create([ 'dpa' =>  "26.06", 'nombre' => "Caibarién" ]);
        Municipio::create([ 'dpa' =>  "28.01", 'nombre' => "Yaguajay" ]);
        Municipio::create([ 'dpa' =>  "30.05", 'nombre' => "Nuevitas" ]);
        Municipio::create([ 'dpa' =>  "26.07", 'nombre' => "Remedios" ]);
        Municipio::create([ 'dpa' =>  "26.08", 'nombre' => "Placetas" ]);
        Municipio::create([ 'dpa' =>  "29.02", 'nombre' => "Morón" ]);
        Municipio::create([ 'dpa' =>  "28.04", 'nombre' => "Cabaiguán" ]);
        Municipio::create([ 'dpa' =>  "28.05", 'nombre' => "Fomento" ]);
        Municipio::create([ 'dpa' =>  "28.03", 'nombre' => "Taguasco" ]);
        Municipio::create([ 'dpa' =>  "29.06", 'nombre' => "Florencia" ]);
        Municipio::create([ 'dpa' =>  "28.02", 'nombre' => "Jatibonico" ]);
        Municipio::create([ 'dpa' =>  "29.05", 'nombre' => "Ciro Redondo" ]);
        Municipio::create([ 'dpa' =>  "29.03", 'nombre' => "Bolivia" ]);
        Municipio::create([ 'dpa' =>  "29.04", 'nombre' => "Primero de Enero" ]);
        Municipio::create([ 'dpa' =>  "28.07", 'nombre' => "Sancti Spíritus" ]);
        Municipio::create([ 'dpa' =>  "29.07", 'nombre' => "Majagua" ]);
        Municipio::create([ 'dpa' =>  "30.02", 'nombre' => "Esmeralda" ]);
        Municipio::create([ 'dpa' =>  "29.08", 'nombre' => "Ciego de Ávila" ]);
        Municipio::create([ 'dpa' =>  "30.03", 'nombre' => "Sierra de Cubitas" ]);
        Municipio::create([ 'dpa' =>  "29.10", 'nombre' => "Baraguá" ]);
        Municipio::create([ 'dpa' =>  "29.09", 'nombre' => "Venezuela" ]);
        Municipio::create([ 'dpa' =>  "30.04", 'nombre' => "Minas" ]);
        Municipio::create([ 'dpa' =>  "30.01", 'nombre' => "Carlos Manuel de Céspedes" ]);
        Municipio::create([ 'dpa' =>  "28.08", 'nombre' => "La Sierpe" ]);
        Municipio::create([ 'dpa' =>  "30.09", 'nombre' => "Florida" ]);
        Municipio::create([ 'dpa' =>  "30.08", 'nombre' => "Camagüey" ]);
        Municipio::create([ 'dpa' =>  "30.06", 'nombre' => "Guáimaro" ]);
        Municipio::create([ 'dpa' =>  "30.07", 'nombre' => "Sibanicú" ]);
        Municipio::create([ 'dpa' =>  "31.01", 'nombre' => "Manatí" ]);
        Municipio::create([ 'dpa' =>  "30.10", 'nombre' => "Vertientes" ]);
        Municipio::create([ 'dpa' =>  "30.11", 'nombre' => "Jimaguayú" ]);
        Municipio::create([ 'dpa' =>  "31.03", 'nombre' => "Jesús Menéndez" ]);
        Municipio::create([ 'dpa' =>  "31.02", 'nombre' => "Puerto Padre" ]);
        Municipio::create([ 'dpa' =>  "32.03", 'nombre' => "Banes" ]);
        Municipio::create([ 'dpa' =>  "30.13", 'nombre' => "Santa Cruz del Sur" ]);
        Municipio::create([ 'dpa' =>  "32.01", 'nombre' => "Gibara" ]);
        Municipio::create([ 'dpa' =>  "30.12", 'nombre' => "Najasa" ]);
        Municipio::create([ 'dpa' =>  "32.02", 'nombre' => "Rafael Freyre" ]);
        Municipio::create([ 'dpa' =>  "31.05", 'nombre' => "Las Tunas" ]);
        Municipio::create([ 'dpa' =>  "32.07", 'nombre' => "Calixto García" ]);
        Municipio::create([ 'dpa' =>  "32.06", 'nombre' => "Holguín" ]);
        Municipio::create([ 'dpa' =>  "31.06", 'nombre' => "Jobabo" ]);
        Municipio::create([ 'dpa' =>  "31.07", 'nombre' => "Colombia" ]);
        Municipio::create([ 'dpa' =>  "31.08", 'nombre' => "Amancio" ]);
        Municipio::create([ 'dpa' =>  "31.04", 'nombre' => "Majibacoa" ]);
        Municipio::create([ 'dpa' =>  "32.05", 'nombre' => "Báguanos" ]);
        Municipio::create([ 'dpa' =>  "32.04", 'nombre' => "Antilla" ]);
        Municipio::create([ 'dpa' =>  "32.11", 'nombre' => "Mayarí" ]);
        Municipio::create([ 'dpa' =>  "32.08", 'nombre' => "Cacocum" ]);
        Municipio::create([ 'dpa' =>  "33.01", 'nombre' => "Río Cauto" ]);
        Municipio::create([ 'dpa' =>  "32.14", 'nombre' => "Moa" ]);
        Municipio::create([ 'dpa' =>  "33.02", 'nombre' => "Cauto Cristo" ]);
        Municipio::create([ 'dpa' =>  "32.12", 'nombre' => "Frank País" ]);
        Municipio::create([ 'dpa' =>  "32.10", 'nombre' => "Cueto" ]);
        Municipio::create([ 'dpa' =>  "32.09", 'nombre' => "Urbano Noris" ]);
        Municipio::create([ 'dpa' =>  "32.13", 'nombre' => "Sagua de Tánamo" ]);
        Municipio::create([ 'dpa' =>  "34.04", 'nombre' => "Segundo Frente" ]);
        Municipio::create([ 'dpa' =>  "33.04", 'nombre' => "Bayamo" ]);
        Municipio::create([ 'dpa' =>  "33.03", 'nombre' => "Jiguaní" ]);
        Municipio::create([ 'dpa' =>  "35.09", 'nombre' => "Guantánamo" ]);
        Municipio::create([ 'dpa' =>  "34.02", 'nombre' => "Mella" ]);
        Municipio::create([ 'dpa' =>  "35.03", 'nombre' => "Yateras" ]);
        Municipio::create([ 'dpa' =>  "34.01", 'nombre' => "Contramaestre" ]);
        Municipio::create([ 'dpa' =>  "33.05", 'nombre' => "Yara" ]);
        Municipio::create([ 'dpa' =>  "34.03", 'nombre' => "San Luis" ]);
        Municipio::create([ 'dpa' =>  "34.07", 'nombre' => "Palma Soriano" ]);
        Municipio::create([ 'dpa' =>  "35.01", 'nombre' => "El Salvador" ]);
        Municipio::create([ 'dpa' =>  "33.06", 'nombre' => "Manzanillo" ]);
        Municipio::create([ 'dpa' =>  "34.05", 'nombre' => "Songo La Maya" ]);
        Municipio::create([ 'dpa' =>  "33.13", 'nombre' => "Guisa" ]);
        Municipio::create([ 'dpa' =>  "34.08", 'nombre' => "Tercer Frente" ]);
        Municipio::create([ 'dpa' =>  "33.12", 'nombre' => "Buey Arriba" ]);
        Municipio::create([ 'dpa' =>  "35.02", 'nombre' => "Manuel Tames" ]);
        Municipio::create([ 'dpa' =>  "33.11", 'nombre' => "Bartolomé Masó" ]);
        Municipio::create([ 'dpa' =>  "35.10", 'nombre' => "Niceto Pérez" ]);
        Municipio::create([ 'dpa' =>  "33.08", 'nombre' => "Media Luna" ]);
        Municipio::create([ 'dpa' =>  "34.06", 'nombre' => "Santiago de Cuba" ]);
        Municipio::create([ 'dpa' =>  "34.09", 'nombre' => "Guamá" ]);
        Municipio::create([ 'dpa' =>  "35.08", 'nombre' => "Caimanera" ]);
        Municipio::create([ 'dpa' =>  "35.07", 'nombre' => "San Antonio del Sur" ]);
        Municipio::create([ 'dpa' =>  "33.09", 'nombre' => "Niquero" ]);
        Municipio::create([ 'dpa' =>  "33.10", 'nombre' => "Pilón" ]);
        Municipio::create([ 'dpa' =>  "35.04", 'nombre' => "Baracoa" ]);
        Municipio::create([ 'dpa' =>  "35.06", 'nombre' => "Imías" ]);
        Municipio::create([ 'dpa' =>  "35.05", 'nombre' => "Maisí" ]);
        Municipio::create([ 'dpa' =>  "33.07", 'nombre' => "Campechuela" ]);
        Municipio::create([ 'dpa' =>  "36.00", 'nombre' => "Municipio Especial Isla de la Juventud" ]);
    }
}
